config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :flats do
    resources :reservations
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  geocoded_by :address  
  after_validation :geocode, if: :address_changed?

  include PgSearch::Model
  pg_search_scope :search_by_address,
    against: [ :address ],
    using: {
      tsearch: { prefix: true }
    }
end

app/models/reservation.rb
class Reservation < ApplicationRecord
  belongs_to :user
  belongs_to :flat
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit

  # Pundit: white-list approach.
  # after_action :verify_authorized, except: :index, unless: :skip_pundit?
  # after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

    # Uncomment when you *really understand* Pundit!
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(request.referrer || root_path)
  end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :email, :phone_number])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :email, :phone_number])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
   # Not required since everyone can see flats before_action :authenticate_user!
  def index
    @flats = policy_scope(Flat)

    if params[:query].present?
      @flats = Flat.search_by_address(params[:query])
      @markers = @flats.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
      end
    else
      @flats = Flat.all
      @markers = @flats.geocoded.map do |flat|
        {
          lat: flat.latitude,
          lng: flat.longitude
        }
      end
    end
  end

  def show
    @flats = Flat.find(params[:id])
    authorize @flats
  end

  def new
    @flat = Flat.new
    authorize @flat
  end

  def create
    @flat = Flat.new(flat_params)
    authorize @flat
    @flat.user = current_user
    @flat.save
    redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
    authorize @flat
  end

  def update
    @flat = Flat.find(params[:id])
    authorize @flat
    @flat.update(flat_params)
    redirect_to flats_path
  end

  def destroy
    @flat = Flat.find(params[:id])
    authorize @flat
    @flat.destroy
    redirect_to flats_path
  end

  private

  def flat_params

    params.require(:flat).permit(:price, :description, :address, :user_id, :availability_start_date, :availability_end_date, :title, :city, :zip, :bedroom, :restroom, :bed, photos: [])
  end
end


# create_table "flats", force: :cascade do |t|
#     t.integer "price"
#     t.text "description"
#     t.text "address"
#     t.date "availability_start_date"
#     t.date "availability_end_date"
#     t.string "title"
#     t.datetime "created_at", precision: 6, null: false
#     t.datetime "updated_at", precision: 6, null: false
#   end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
  end
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  before_action :authenticate_user!

  def index
    @reservations = policy_scope(Reservation)
  end

  def show
    @reservation = Reservation.find(params[:id])
    authorize @reservation
  end

  def new
    @flat = Flat.find(params[:flat_id])
    @reservation = Reservation.new
    authorize @reservation
  end

  def create
    @reservation = Reservation.new(reservation_params)
    authorize @reservation
    @reservation.user = current_user

    flat = Flat.find(params[:flat_id])
    @reservation.flat = flat

    if @reservation.save
      redirect_to flat_reservations_path, notice: 'Reservation was successfully created'
    else
      render :new
    end
  end

  def edit
    @flat = Flat.find(params[:flat_id])
    @reservation = Reservation.find(params[:id])

    authorize @reservation
  end

  def update
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.update(reservation_params)

    redirect_to flat_reservation_path(@reservation.flat, @reservation)
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    authorize @reservation
    @reservation.destroy

    redirect_to flat_reservations_path(:id)
  end

  private

  def reservation_params
    params.require(:reservation).permit(:price, :start_date, :end_date)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/flats/edit.html.erb
<h1 class="border-bottom">Edit Flat</h1>
<div class="container-user-form">
  <div class= 'divider'>
    <div class='row justify-content-center'>
      <div class="col-6"> 

        <ul>

          <%= simple_form_for [@flat] do |f| %>
          <li>
            <%= f.input :price, as: :integer %>
          </li>
          <li>
            <%= f.input :address %>
          </li>
          <li>
            <%= f.input :availability_start_date, as: :date %>
          </li>
          <li>
            <%= f.input :availability_end_date, as: :date %>
          </li>
          <li>
            <%= f.input :photos, as: :file, input_html: { multiple: true } %>
          </li>
          <li>
            <%= f.submit %>
          </li>
        </ul>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/flats/index.html.erb
<h1 class="border-bottom">Our Available Homes</h1>
  <div class="flex-container">
    <h3>Search on another city</h3>
  

    <div class="search-bar-flats">
        <%= form_tag flats_path, method: :get do %>
        <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Find a house"
        %>
        <%= submit_tag "Search", class: "btn btn-ghost" %>
        <% end %>
    </div>
  </div>
  

<div class="main-container">

    <div class="container-form">
        <div class='row justify-content-center'>
        <div id="map"
            style="width: 60%; height: 400px; margin-top: 0px; margin-bottom: 20px;"
            data-markers="<%= @markers.to_json %>"
            data-mapbox-api-key="pk.eyJ1IjoiZGF2aWRsdWdvMTAiLCJhIjoiY2tsMnBycGFvMGI2ajJucDdzeTc1bmg3diJ9.OIpMWRQo9NRtxDnU52PUmQ">
        </div> 
    </div>

    <div class="row justify-content-center">
        <div class="btn-group", id="route_buttons">
            <%# <%= link_to "Home Page", root_path, class: "btn btn-primary btn-sm", id: "Home" %>
            <%= link_to "Create a new flat", new_flat_path, class: "btn btn-primary btn-sm", id: "New" %>
        </div>
    </div>


    <div class="container">
        <% @flats.each do |flat|%>

        <div class="card" style="height:550px;">
           <%= link_to flat_path(flat) do %> 
            <div class="card-photo">
                <% if flat.photos.any? %>
                    <%= image_tag flat.photos.first, class: "card-img-top"%>
                <%else%>
                    <img class="card-img-top" src="https://images.adsttc.com/media/images/5e1d/02c3/3312/fd58/9c00/06e9/slideshow/NewHouse_SA_Photo_01.jpg?1578959519" alt="Card image cap">
                <%end%>
            </div>
          <%end%>
            <div class="card-body">
                <h4 class="card-title"><%= flat.title %> </h4>
                <h5 class="card-price"><%= "$ #{flat.price}" %> </h5>
                <h6 class="card-address"><%= flat.address %> </h6>
                <p class="card-description"><%= flat.description %> </p>
                <div class="buttons-bottom">
                <% if flat.user == current_user %>
                    <a><%= link_to "Update Flat", edit_flat_path(flat), class: "btn btn-primary" %> </a>
                    <a><%= link_to "Delete Flat", flat_path(flat), method: "delete", class: "btn btn-danger", data: { confirm: "Are you sure?" } %> </a>
                <% else %>
                    <a><%= link_to "Rent this Flat", new_flat_reservation_path(flat), class: "btn btn-primary" %> </a>
                <% end %>

                </div>
            </div>

        </div>
        <% end %>
    </div>
</div>

app/views/flats/new.html.erb
<h1 class="border-bottom">New Flat</h1>
<div class="container-user-form">
  <div class= 'divider'>
    <div class='row justify-content-center'>
        <div class="col-6"> 
          <ul>
            <%= simple_form_for [@flat] do |f| %>

            <li>
              <%= f.input :title, as: :text  %>
            </li>
            <li>
              <%= f.input :description, as: :text  %>
            </li>
                <li>
              <%= f.input :address, as: :text  %>
            </li>
                <li>
              <%= f.input :city, as: :string  %>
            </li>
            <li>
              <%= f.input :zip %>
            </li>
            <li>
              <%= f.input :bedroom %>
            </li>
            <li>
              <%= f.input :bed %>
            </li>
            <li>
              <%= f.input :restroom %>
            </li>
            <li>
              <%= f.input :price %>
            </li>
              <li>
              <%= f.input :availability_start_date, as: :date  %>
            </li>
              <li>
              <%= f.input :availability_end_date, as: :date  %>
            </li>
            <li>
              <%= f.input :photos, as: :file, input_html: { multiple: true } %>
            </li>
            <li>
              <%= f.submit %>
            </li>
          </ul>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
 <div class="container-user-form">
  <div class= 'divider'>
    <div class='row justify-content-center'>
      <div class="col-6"> 
        <div>
            <div class="container-fluid">
              <img src="https://source.unsplash.com/random" class="d-block w-100" alt="...">
              <h2 id="title"><%= @flats.title %></h2>
              <h4>Price $:<%= @flats.price %></h4>
              <p><%= @flats.description %></p>
              <p><%= @flats.address %></p>
              <p><%= @flats.city %></p>
              <p>Bedrooms: <%= @flats.bedroom %></p>
              <p>Beds: <%= @flats.bed %></p>
              <p>Bathrooms: <%= @flats.restroom %></p>
              <p>Available start date: <%= @flats.availability_start_date %></p>
              <p>Available end date: <%= @flats.availability_end_date %></p> 
              <div class='row justify-content-center'>
                <a><%= link_to "Reserve Flat", new_flat_reservation_path(@flats), class: "btn btn-ghost"%> </a>
              </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    

    
    <link rel="stylesheet" href="path/to/font-awesome/css/font-awesome.min.css">
    <link href='https://api.mapbox.com/mapbox-gl-js/v1.11.1/mapbox-gl.css' rel='stylesheet' />

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= stylesheet_pack_tag 'application' %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1601961782438-9d442fa2f450?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1949&q=80);">
  <div class="flex-container">
    <h1>Where would you like to live next?</h1>
  </div>

  <div class="search-bar">
    <%= form_tag flats_path, method: :get do %>
      <%= text_field_tag :query,
        params[:query],
        class: "form-control",
        placeholder: "Find a house"
      %>
      <%= submit_tag "Search", class: "btn btn-primary" %>
    <% end %>
  </div>

  

</div>
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Brought to you by Best's Le Wagon Crew! <i class="fas fa-heart"></i> 
  </div>
</div>

app/views/reservations/edit.html.erb
<h1 class="border-bottom">Edit Reservation</h1>
  <div class="container-user-form">
    <div class= 'divider'>
      <div class='row justify-content-center'>
        <div class="col-6">     
          <ul>
            <%= simple_form_for [@flat, @reservation] do |f| %>
            <li>
              <%= f.input :start_date, as: :date, html5: true %>
            </li>
            <li>
              <%= f.input :end_date, as: :date, html5: true %>
            </li>
            <li>
              <%= f.submit %>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/reservations/index.html.erb
<h1 class="border-bottom">My Reservations</h1>

<%=link_to "New Reservation", flats_path, class: "btn btn-primary" %>


<div class='reservation-list'>
  
  <% @reservations.each do |reservation|%>
   <div class="card-trip">
  <img src="https://source.unsplash.com/random" />
  <div class="card-trip-infos">
    <div>
      <h2><%= reservation.flat.title %></h2>
      <p>Start Date: <%= reservation.start_date %> </p>
      <p>End Date: <%= reservation.end_date %> </p>
    </div>
    <h2 class="card-trip-pricing">Price: $<%= reservation.price %> </h2>
    
  </div>
  <%= link_to "Update Reservation", edit_flat_reservation_path(reservation.flat, reservation), class: "btn btn-primary" %>
 <%= link_to "" , flat_reservation_path(reservation.flat, reservation), method: :delete, data: { confirm: "Are you sure?" }, class:"fas fa-trash-alt" %>
</div>

  <% end %>
</div> 
 

app/views/reservations/new.html.erb
<h1 class="border-bottom">New Reservation</h1>
   <div class="container-user-form">
    <div class= 'divider'>
      <div class='row justify-content-center'>
        <div class="col-6">  
          <ul>
            <%= simple_form_for [@flat, @reservation] do |f| %>
            <li>
              <%= f.input :start_date, as: :date, html5: true %>
            </li>
            <li>
              <%= f.input :end_date, as: :date, html5: true %>
            </li>
            <li>
              <%= f.submit %>
            </li>
          </ul>
          <% end %>
        </div>
      </div>
    </div>
  </div>

app/views/reservations/show.html.erb
<h2>New start date: <%= @reservation.start_date %></h2>
<h2> New end date: <%= @reservation.end_date %></h2>

<%= link_to "Back to my reservations", flat_reservations_path %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li> 
        <li class="nav-item">
          <%= link_to "Flats", flats_path, class: "nav-link" %>
        </li>
        <!-- <li class="nav-item">
          <%= link_to "Search", flat_path(:id), class: "nav-link" %>
        </li> -->
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Rent a Flat", flats_path, class: "dropdown-item" %>
            <%= link_to "Reservations", flat_reservations_path(:id), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<!-- method: "get", action: "index", controller: "reservations", class: "nav-link", -->